# Build stage for webhook stub
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Копируем go.mod/go.sum для кэширования зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники
COPY . .

# Сборка бинарника
RUN CGO_ENABLED=0 GOOS=linux go build -o webhookstub ./webhook-stub

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/webhookstub .

EXPOSE 9090

CMD ["./webhookstub"]

